import { alphabet } from "@/shared/config";
import { bookResult } from "@/shared/types";

let cache: Record<string, any> = {};

/**
 * Checks if the description is autogenerated by Google
 * @param description The description to check
 * @returns boolean - Whether the description is autogenerated
 */
function isBoilerplate(description: string) {
	return /^.{0,200} by .{0,100} released .{0,100} available now for purchase\.?$/i.test(
		description.trim(),
	);
}

/**
 * Replaces all instances of the title and author from the description string
 * @param books The selected array of simplified book objects
 * @returns The selected array of simplified book objects, now with censored descriptions
 */
function censorBooks(books: bookResult[]) {
	for (let i = 0; i < books.length; i++) {
		const currentBook = books[i].volumeInfo;

		books[i].censoredDescription = currentBook.description.replaceAll(
			currentBook.title,
			"TITLE",
		);

		if (currentBook.authors) {
			currentBook.authors.forEach((author: string, index) => {
				const assignedLetter =
					currentBook.authors.length > 1 ? " " + alphabet[index] : "";
				const authorRegex = new RegExp(`\\b${author}\\b`, "gi");

				const lastName = author.trim().split(/\s+/).pop() ?? "";
				const lastNameRegex = new RegExp(`\\b${lastName}\\b`, "gi");

				const authorString = "AUTHOR" + assignedLetter;
				const lastNameString = "LAST NAME" + assignedLetter;

				books[i].censoredDescription = books[i].censoredDescription
					.replaceAll(authorRegex, authorString)
					.replaceAll(lastNameRegex, lastNameString);
			});
		}
	}

	return books;
}

/**
 * Fetches books from the API
 * @param url The url to fetch
 * @returns resData - The results from the call
 */
export async function apiCall(url: string, retries = 4): Promise<{ totalItems: number; items: bookResult[]; error: string; } | null> {
    const baseBackoff = 1200; // ms - increase base so we wait longer between attempts
    const maxJitter = 800;

    for (let attempt = 0; attempt <= retries; attempt++) {
        try {
            const response = await fetch(url);
            const status = response.status;
            const textBody = await response.text().catch(() => "");
            let resData: any = null;
            try { resData = textBody ? JSON.parse(textBody) : null; } catch { resData = textBody; }

            if (response.ok) {
                return resData || null;
            }

            console.log(`[apiCall] attempt=${attempt} status=${status}`);

            // If service indicates when to retry, honor it
            const retryAfter = response.headers?.get?.("retry-after");
            if ((status === 429 || status === 503 || (status >= 500 && status < 600)) && attempt < retries) {
                let waitMs = baseBackoff * Math.pow(2, attempt) + Math.floor(Math.random() * maxJitter);
                if (retryAfter) {
                    const ra = Number(retryAfter);
                    if (!Number.isNaN(ra)) waitMs = Math.max(waitMs, ra * 1000);
                }
                console.log(`[apiCall] retrying after ${waitMs}ms (retry-after: ${retryAfter}) body:`, textBody);
                await new Promise((r) => setTimeout(r, waitMs));
                continue;
            }

            // non-retryable or exhausted retries: log full body and return null
            console.log("[apiCall] final response body:", textBody);
            return null;
        } catch (err) {
            // network/other error: back off and retry
            console.log(`[apiCall] network error attempt=${attempt}`, err);
            if (attempt < retries) {
                const waitMs = baseBackoff * Math.pow(2, attempt) + Math.floor(Math.random() * maxJitter);
                await new Promise((r) => setTimeout(r, waitMs));
                continue;
            }
            return null;
        }
    }

    return null;
}

/**
 * Uses Fisher-Yates to shuffle the results
 * @param selectedData - The book results to shuffle
 * @returns A shuffled array
 */
function shuffleBooks(selectedData: bookResult[]) {
	for (let i = selectedData.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[selectedData[i], selectedData[j]] = [selectedData[j], selectedData[i]];
	}
	return selectedData;
}

/**
 * Filters results by description quality, censors, and randomizes
 * @param selectedData 
 * @returns 
 */
function curateBooks(selectedData: bookResult[]) {
	if (!selectedData || selectedData.length === 0) {
		return [];
	}

	const filteredData =
		selectedData.filter(
			(item) =>
				!!item.volumeInfo.description &&
				item.volumeInfo.description.length >= 100 &&
				!isBoilerplate(item.volumeInfo.description),
		) || [];

	const censoredBooks = censorBooks(filteredData);
	const shuffledBooks = shuffleBooks(censoredBooks);

	return shuffledBooks;
}

/**
 * Gets as many results as possible, up to 1000
 * @param querystring Either the subject or search query to look for
 * @returns 
 */
async function batchCallBooks(querystring: string) {
    let results: bookResult[] = [];

    const key = process.env.API_KEY;
    if (!key) {
        console.warn("[batchCallBooks] Missing API_KEY");
        return results;
    }

    // Get totalItems first so we only request what's needed
    const totalResp = await apiCall(
        `https://www.googleapis.com/books/v1/volumes?q=${querystring}&langRestrict=en&maxResults=1&fields=totalItems&key=${key}`,
    );
    const totalItems = totalResp?.totalItems ?? 0;
    if (!totalItems) return results;

    const maxItems = Math.min(totalItems, 1000);
    const pageSize = 40;

    for (let i = 0; i < maxItems; i += pageSize) {
        const currentBatch = await apiCall(
            `https://www.googleapis.com/books/v1/volumes?q=${querystring}&langRestrict=en&maxResults=${pageSize}&startIndex=${i}&fields=items(id,volumeInfo/title,volumeInfo/authors,volumeInfo/description)&key=${key}`,
        );

        if (!currentBatch || !currentBatch.items || currentBatch.items.length === 0) {
            break;
        }

        // append in order
        results = [...results, ...currentBatch.items];

        // longer delay to reduce chance of rate limiting
        await new Promise((resolve) => setTimeout(resolve, 1500));
    }

    return results;
}

/**
 * Gets the book descriptions based on user-selected keywords
 * @param params The keyword to use for the search
 * @param q (optional) The user's custom query
 * @returns An array of books with censored descriptions
 */
export async function getBooks(
	params: string,
	q?: string,
) {
	// Find out how many total results there are
	const paramsQuery =
		params && params !== "search" ? `subject:"${params}"` : null;
	const customQuery = params === "search" && q ? q : null;
	const querystring = customQuery || paramsQuery || '';

	// Get as many results as possible, then filter for quality and randomize
	const selectedData: bookResult[] = await batchCallBooks(querystring);

	const finalResults = curateBooks(selectedData);

	if (finalResults.length > 0) {
		cache[`books:${querystring}`] = {finalResults, timestamp: Date.now()};
	} else if (cache[`books:${querystring}`]) {
		// If we have a cached result, use it
		console.log('Using cached results for query:', querystring);
		return cache[`books:${querystring}`].finalResults;
	}

	return finalResults;
}
