import { alphabet } from "@/shared/config";
import { bookResult } from "@/shared/types";

/**
 * Checks if the description is autogenerated by Google
 * @param description The description to check
 * @returns boolean - Whether the description is autogenerated
 */
function isBoilerplate(description: string) {
	return /^.{0,200} by .{0,100} released .{0,100} available now for purchase\.?$/i.test(
		description.trim(),
	);
}

/**
 * Replaces all instances of the title and author from the description string
 * @param books The selected array of simplified book objects
 * @returns The selected array of simplified book objects, now with censored descriptions
 */
function censorBooks(books: bookResult[]) {
	for (let i = 0; i < books.length; i++) {
		const currentBook = books[i].volumeInfo;

		books[i].censoredDescription = currentBook.description.replaceAll(
			currentBook.title,
			"TITLE",
		);

		if (currentBook.authors) {
			currentBook.authors.forEach((author: string, index) => {
				const assignedLetter =
					currentBook.authors.length > 1 ? " " + alphabet[index] : "";
				const authorRegex = new RegExp(`\\b${author}\\b`, "gi");

				const lastName = author.trim().split(/\s+/).pop() ?? "";
				const lastNameRegex = new RegExp(`\\b${lastName}\\b`, "gi");

				const authorString = "AUTHOR" + assignedLetter;
				const lastNameString = "LAST NAME" + assignedLetter;

				books[i].censoredDescription = books[i].censoredDescription
					.replaceAll(authorRegex, authorString)
					.replaceAll(lastNameRegex, lastNameString);
			});
		}
	}

	return books;
}

/**
 * Fetches books from the API
 * @param url The url to fetch
 * @returns resData - The results from the call
 */
export async function apiCall(url: string) {
	const response = await fetch(url);
	const resData = await response.json();

	if (!response.ok) {
		throw new Error("Failed to fetch books.");
	}

	return resData;
}

/**
 * Uses Fisher-Yates to shuffle the results
 * @param selectedData - The book results to shuffle
 * @returns A shuffled array
 */
function shuffleBooks(selectedData: bookResult[]) {
	for (let i = selectedData.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[selectedData[i], selectedData[j]] = [selectedData[j], selectedData[i]];
	}
	return selectedData;
}

/**
 * Filters results by description quality, censors, and randomizes
 * @param selectedData 
 * @returns 
 */
function curateBooks(selectedData: bookResult[]) {
	if (!selectedData || selectedData.length === 0) {
		return [];
	}

	const filteredData =
		selectedData.filter(
			(item) =>
				!!item.volumeInfo.description &&
				item.volumeInfo.description.length >= 100 &&
				!isBoilerplate(item.volumeInfo.description),
		) || [];

	const censoredBooks = censorBooks(filteredData);
	const shuffledBooks = shuffleBooks(censoredBooks);

	return shuffledBooks;
}

/**
 * Gets as many results as possible, up to 1000
 * @param querystring Either the subject or search query to look for
 * @returns 
 */
async function batchCallBooks(querystring: string) {
	let results: bookResult[] = [];

	for (let i = 0; i < 1000; i += 20) {
		const currentBatch = await apiCall(
			`https://www.googleapis.com/books/v1/volumes?q=${querystring}&langRestrict=en&maxResults=20&startIndex=${i}&fields=totalItems,items(id,volumeInfo/title,volumeInfo/authors,volumeInfo/description)`,
		);

		if (!currentBatch.items || currentBatch.items.length === 0) {
			break;
		}

		results = [...currentBatch.items, ...results];

		// Wait before making a new call
		await new Promise((resolve) => setTimeout(resolve, 300));
	}

	return results;
}

/**
 * Gets the book descriptions based on user-selected keywords
 * @param params The keyword to use for the search
 * @param q (optional) The user's custom query
 * @returns An array of books with censored descriptions
 */
export async function getBooks(
	params: string,
	q?: string,
) {
	// Find out how many total results there are
	const paramsQuery =
		params && params !== "search" ? `subject:${params}` : null;
	const customQuery = params === "search" && q ? q : null;
	const querystring = customQuery || paramsQuery || '';

	// Get as many results as possible, then filter for quality and randomize
	const selectedData: bookResult[] = await batchCallBooks(querystring);

	const finalResults = curateBooks(selectedData);

	return finalResults;
}
