import { limit, alphabet } from "@/shared/config";
import { bookResult } from "@/shared/types";

/**
 * Picks out a random range of results from the API, within the configured limit
 * @param maximum - The total length of the results
 * @returns A random integer for the index value
 */
function getRandomRange(maximum: number) {
	let max = maximum - limit;
	if (max > 100) {
		// startIndex results are inconsistent beyond 100
		max = 100 - limit;
	}

	return Math.floor(Math.random() * (max + 1));
}

/**
 * Checks if the description is autogenerated by Google
 * @param description The description to check
 * @returns boolean - Whether the description is autogenerated
 */
function isBoilerplate(description: string) {
	return /^.{0,200} by .{0,100} released .{0,100} available now for purchase\.?$/i.test(
		description.trim(),
	);
}

/**
 * Replaces all instances of the title and author from the description string
 * @param books The selected array of simplified book objects
 * @returns The selected array of simplified book objects, now with censored descriptions
 */
function censorBooks(books: bookResult[]) {
	for (let i = 0; i < books.length; i++) {
		const currentBook = books[i].volumeInfo;

		books[i].volumeInfo.description = currentBook.description.replaceAll(
			currentBook.title,
			"TITLE",
		);

		if (currentBook.authors) {
			currentBook.authors.forEach((author: string, index) => {
				const assignedLetter =
					currentBook.authors.length > 1 ? " " + alphabet[index] : "";
				const authorRegex = new RegExp(`\\b${author}\\b`, "gi");

				const lastName = author.trim().split(/\s+/).pop() ?? "";
				const lastNameRegex = new RegExp(`\\b${lastName}\\b`, "gi");

				const authorString = "AUTHOR" + assignedLetter;
				const lastNameString = "LAST NAME" + assignedLetter;

				books[i].volumeInfo.description = books[i].volumeInfo.description
					.replaceAll(authorRegex, authorString)
					.replaceAll(lastNameRegex, lastNameString);
			});
		}
	}

	return books;
}

/**
 * Fetches books from the API
 * @param url The url to fetch
 * @returns resData - The results from the call
 */
export async function apiCall(url: string) {
	const response = await fetch(url);
	const resData = await response.json();

	if (!response.ok) {
		throw new Error("Failed to fetch books.");
	}

	return resData;
}

function curateResults(selectedData: {items: bookResult[]}) {
	if (!selectedData.items || selectedData.items.length === 0) {
		return [];
	}

	const filteredData =
		selectedData.items?.filter(
			(item) =>
				!!item.volumeInfo.description &&
				item.volumeInfo.description.length >= 100 &&
				!isBoilerplate(item.volumeInfo.description),
		) || [];

	// Remove all mentions of the title and author from the descriptions
	const censoredBooks = censorBooks(filteredData);

	return censoredBooks;
}

/**
 * Gets the book descriptions based on user-selected keywords
 * @param params The keyword to use for the search
 * @param randomLetter A random letter added to further randomization of the search
 * @param q (optional) The user's custom query
 * @returns An array of books with censored descriptions
 */
export async function getBooks(params: string, randomLetter: string, q: string|undefined) {
	// Find out how many total results there are
	const paramsQuery = params && params !== 'search' ? `subject:${params}` : null;
	const customQuery = params === 'search' && q ? q : null;
	const querystring = customQuery || paramsQuery;

	const initialData = await apiCall(
		`https://www.googleapis.com/books/v1/volumes?q=${querystring}+${randomLetter}&langRestrict=en&maxResults=40&fields=totalItems`,
	);
	const totalResults = initialData.totalItems;

	// Find a random start index
	const startIndex = getRandomRange(totalResults);

	// Pull 40 results starting from the random start index
	let selectedData: { items: bookResult[] } = await apiCall(
		`https://www.googleapis.com/books/v1/volumes?q=${querystring}+${randomLetter}&langRestrict=en&maxResults=40&startIndex=${startIndex}&fields=totalItems,items(id,volumeInfo/title,volumeInfo/authors,volumeInfo/description)`,
	);

	let finalResults = curateResults(selectedData);

	// If the randomization results in nothing, start again from the top
	if (finalResults.length === 0) {
		selectedData = await apiCall(
			`https://www.googleapis.com/books/v1/volumes?q=${querystring}&langRestrict=en&maxResults=40&startIndex=0&fields=totalItems,items(id,volumeInfo/title,volumeInfo/authors,volumeInfo/description)`,
		);
		finalResults = curateResults(selectedData);
	}

	return finalResults;
}
